### PR TITLE
Replace startOfWork/endOfWork calls with RAII pattern …

### PR DESCRIPTION
**Pull request by TimSylvester-mousebird**

### CODE REVIEW

**Comment by mousebird** [comment]
I wonder if we could have a constructor for WorkRegion that took a renderControl.  Then we could check that it was not null before dereferencing interactLayer.

**Review by mousebird — APPROVED** [review]

**Comment by mousebird** [comment]
I like this pattern.  Should be good.

**Comment by TimSylvester-mousebird** [comment]
> I wonder if we could have a constructor for WorkRegion that took a renderControl. Then we could check that it was not null before dereferencing interactLayer.

I used a `NSObject<MaplyRenderControllerProtocol>` to match the way it's used in `MapboxVectorInterpreter`, are you saying it should reference `MaplyRenderController` directly?

**Comment by mousebird** [comment]
I'm worried about losing the !renderController check, mostly.

**Comment by TimSylvester-mousebird** [comment]
Ah, good catch.  I handled that in `MapboxVectorInterpreter` but missed a few in `MaplyBaseViewController`.  See the update above.

**Review by mousebird — APPROVED** [review]

**Comment by mousebird** [comment]
Looks good!

**Pull request merged**
